import type { MailuEnvOptions } from '../types';

export const generateMailuEnv = (opt: MailuEnvOptions) => {
  class EnvBuilder {
    env = '';

    if(condition: boolean, callback: (builder: EnvBuilder) => EnvBuilder) {
      return condition ? callback(this) : this;
    }

    comment(comment?: string) {
      this.env += '#' + (comment ? ` ${comment}` : '') + '\n';
      return this;
    }

    fileHeader(...text: string[]) {
      text.forEach(line => this.comment(line));
      this.env += '\n';
      return this;
    }

    private sectionHeader() {
      this.env += '###################################\n';
      return this;
    }

    section(section: string) {
      this.sectionHeader().comment(section).sectionHeader();
      this.env += '\n';
      return this;
    }

    var(key: string, value: string | boolean, firstComment?: string, ...comments: string[]) {
      if (firstComment) {
        this.comment(firstComment);
      } else {
        this.env.slice(0, -1);
      }
      comments.forEach(comment => this.comment(comment));
      this.env += `${key}=${String(value)}\n\n`;
      return this;
    }

    build() {
      return this.env;
    }
  }

  return new EnvBuilder()
    .fileHeader(
      'Mailu main configuration file',
      '',
      'This file is autogenerated by the configuration management wizard for Mailu-OIDC.',
      'For a detailed list of configuration variables, see the documentation at',
      'https://mailu.io'
    )
    .section('Common configuration variables')
    .var('SECRET_KEY', opt.secret, 'Set to a randomly generated 16 bytes string')
    .var(
      'SUBNET',
      opt.subnet,
      'Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)'
    )
    .if(!!opt.subnet6, env => env.var('SUBNET6', opt.subnet6!))
    .var('DOMAIN', opt.domain, 'Main mail domain')
    .var('HOSTNAMES', opt.hostnames, 'Hostnames for this server, separated with commas')
    .var('POSTMASTER', opt.postmaster, 'Postmaster local part (will append the main mail domain)')
    .var(
      'TLS_FLAVOR',
      opt.tlsFlavor,
      'Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)'
    )
    .if(!!opt.rateLimitAuthIP, env =>
      env.var(
        'AUTH_RATELIMIT_IP',
        `${opt.rateLimitAuthIP}/hour`,
        'Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)'
      )
    )
    .if(!!opt.rateLimitAuthUser, env =>
      env.var(
        'AUTH_RATELIMIT_USER',
        opt.rateLimitAuthUser + '/day',
        'Authentication rate limit per user (regardless of the source-IP)'
      )
    )
    .var(
      'DISABLE_STATISTICS',
      !opt.enableStats,
      'Opt-out of statistics, replace with "True" to opt out'
    )
    .section('Optional features')
    .var('ADMIN', opt.enableAdmin, 'Expose the admin interface (value: true, false)')
    .var(
      'WEBMAIL',
      opt.webmailType,
      'Choose which webmail to run if any (values: roundcube, snappymail, none). To enable this feature, recreate the docker-compose.yml file via setup.'
    )
    .var('API', opt.enableAPI, 'Expose the API interface (value: true, false)')
    .var(
      'WEBDAV',
      opt.enableWebdav,
      'Dav server implementation (value: radicale, none). To enable this feature, recreate the docker-compose.yml file via setup.'
    )
    .var(
      'ANTIVIRUS',
      opt.enableAntivirus ? 'clamav' : 'none',
      'Antivirus solution (value: clamav, none). To enable this feature, recreate the docker-compose.yml file via setup.'
    )
    .var(
      'SCAN_MACROS',
      opt.enableOletools,
      'Scan Macros solution (value: true, false). To enable this feature, recreate the docker-compose.yml file via setup.'
    )
    .section('Mail settings')
    .var(
      'MESSAGE_SIZE_LIMIT',
      opt.messageSizeLimit ?? '50000000',
      'Message size limit in bytes',
      'Default: accept messages up to 50MB',
      'Max attachment size will be 33% smaller'
    )
    .if(!!opt.rateLimitMessage, env =>
      env.var('MESSAGE_RATELIMIT', opt.rateLimitMessage + '/day', 'Message rate limit (per user)')
    )
    .var(
      'RELAYNETS',
      '',
      'Networks granted relay permissions',
      'Use this with care, all hosts in this networks will be able to send mail without authentication!'
    )
    .var('RELAYHOST', opt.relayHost ?? '', 'Will relay all outgoing mails if configured')
    .var('FETCHMAIL_ENABLED', opt.enableFetchmail, 'Enable fetchmail')
    .var('FETCHMAIL_DELAY', opt.fetchmailDelay ?? '600', 'Fetchmail delay in seconds')
    .var(
      'FETCHMAIL_DELIMITER',
      opt.fetchmailDelimiter ?? '+',
      'Recipient delimiter, character used to delimiter localpart from custom address part'
    )
    .var('DMARC_RUA', opt.dmarcRUA ?? opt.postmaster, 'DMARC RUA and RUF email')
    .var('DMARC_RUF', opt.dmarcRUF ?? opt.postmaster)
    .var(
      'WELCOME',
      opt.enableWelcome,
      'Welcome email, enable and set a topic and body if you wish to send welcome',
      'emails to all users.'
    )
    .var('WELCOME_SUBJECT', opt.welcomeSubject ?? 'Welcome to your new email account')
    .var(
      'WELCOME_BODY',
      opt.welcomeBody ??
        'Welcome to your new email account, if you can read this, then it is configured properly!'
    )
    .var(
      'COMPRESSION',
      opt.compression,
      'Maildir Compression',
      'choose compression-method, default: none (value: gz, bz2, zstd)'
    )
    .var(
      'COMPRESS_LEVEL',
      opt.compressionLevel,
      undefined,
      'change compression-level, default: 6 (value: 1-9)'
    )
    .var(
      'FULL_TEXT_SEARCH',
      'en',
      'IMAP full-text search is enabled by default.',
      'Set the following variable to off in order to disable the feature',
      'or a comma separated list of language codes to support'
    )
    .section('Web settings')
    .var(
      'WEBROOT_REDIRECT',
      opt.webmailType !== 'none' ? '/webmail' : opt.enableAdmin ? '/admin' : '',
      'Path to redirect / to'
    )
    .var('WEB_ADMIN', '/admin', 'Path to the admin interface if enabled')
    .var('WEB_WEBMAIL', '/webmail', 'Path to the webmail if enabled')
    .var('WEB_API', '/api', 'Path to the API interface if enabled')
    .var('SITENAME', opt.siteName, 'Website name')
    .var('WEBSITE', opt.website, 'Linked Website URL')
    .if(!!opt.recaptchaSiteKey && !!opt.recaptchaSecretKey, env =>
      env
        .comment('Registration reCAPTCHA settings (warning, this has some privacy impact)')
        .comment('RECAPTCHA_PUBLIC_KEY=' + opt.recaptchaSiteKey)
        .var('RECAPTCHA_SECRET_KEY', opt.recaptchaSecretKey + '\n')
    )
    .if(opt.domainRegistration, env =>
      env.var(
        'DOMAIN_REGISTRATION',
        opt.domainRegistration,
        'Domain registration (remove to disable)'
      )
    )
    .section('Advanced settings')
    .var(
      'COMPOSE_PROJECT_NAME',
      opt.composeProjectName ?? 'mailu',
      'Docker-compose project name, this will prepended to containers names.'
    )
    .var('CREDENTIAL_ROUNDS', '12', 'Number of rounds used by the password hashing algorithm')
    .var('REAL_IP_HEADER', opt.realIpHeader ?? 'X-Real-IP', 'Header to take the real IP from')
    .var(
      'REAL_IP_FROM',
      opt.realIpFrom ?? '',
      'IPs for nginx set_real_ip_from (CIDR list separated by commas)'
    )
    .var(
      'REJECT_UNLISTED_RECIPIENT',
      opt.rejectUnlistedRecipient ? 'yes' : 'no',
      'choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)'
    )
    .var(
      'LOG_LEVEL',
      'INFO',
      'Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)'
    )
    .var(
      'TZ',
      'Etc/UTC',
      'Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones'
    )
    .var('DEFAULT_SPAM_THRESHOLD', '80', 'Default spam threshold used for new users')
    .var(
      'API_TOKEN',
      opt.apiToken,
      'API token required for authenticating to the RESTful API.',
      'This is a mandatory setting for using the RESTful API.'
    )
    .var(
      'FULL_TEXT_SEARCH_ATTACHMENTS',
      opt.enableTika ? 'true' : 'false',
      'Whether tika should be enabled (scan/OCR email attachements). To enable this feature, recreate the docker-compose.yml file via setup.'
    )
    .build();
};
